
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class banking extends javax.swing.JFrame {

    /**
     * Creates new form banking
     */
    public banking() {
        initComponents();
        this.setTitle("M-BANKING SEDERHANA");
        butInfo.setEnabled(false);
        butDeposit.setEnabled(false);
        butTransfer.setEnabled(false);
        butLogout.setEnabled(false);
        butTarik.setEnabled(false);
    }

    static HashMap<String, String> akun = new HashMap<String, String>();
    static HashMap<String, Integer> userSaldo = new HashMap<String, Integer>();
    static String penanda;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panelDasar = new javax.swing.JPanel();
        panelTombol = new javax.swing.JPanel();
        butLogin = new javax.swing.JButton();
        butDeposit = new javax.swing.JButton();
        butLogout = new javax.swing.JButton();
        butInfo = new javax.swing.JButton();
        butTransfer = new javax.swing.JButton();
        butTarik = new javax.swing.JButton();
        butDaftar = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        panelDaftar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dafAkun = new javax.swing.JTextField();
        dafPas = new javax.swing.JTextField();
        dafSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        saldoUser = new javax.swing.JTextField();
        pria = new javax.swing.JRadioButton();
        wanita = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        menuLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logRek = new javax.swing.JTextField();
        logPas = new javax.swing.JPasswordField();
        logSubmit = new javax.swing.JButton();
        suksesLogin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelDeposit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        prosesDepo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        depoUang = new javax.swing.JTextField();
        panelTarik = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        prosesTarik = new javax.swing.JButton();
        tarikSaldo = new javax.swing.JTextField();
        panelTransfer = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rekTujuan = new javax.swing.JTextField();
        saldoTF = new javax.swing.JTextField();
        prosesTransfer = new javax.swing.JButton();
        menuHome = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDasar.setBackground(new java.awt.Color(246, 163, 85));

        panelTombol.setBackground(new java.awt.Color(255, 153, 51));
        panelTombol.setForeground(new java.awt.Color(255, 255, 153));

        butLogin.setBackground(new java.awt.Color(255, 204, 51));
        butLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\user (1).png")); // NOI18N
        butLogin.setText("LOGIN");
        buttonGroup2.add(butLogin);
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        butDeposit.setBackground(new java.awt.Color(255, 204, 51));
        butDeposit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butDeposit.setText("DEPOSIT");
        buttonGroup1.add(butDeposit);
        butDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDepositActionPerformed(evt);
            }
        });

        butLogout.setBackground(new java.awt.Color(255, 204, 51));
        butLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butLogout.setText("LOGOUT");
        buttonGroup1.add(butLogout);
        butLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogoutActionPerformed(evt);
            }
        });

        butInfo.setBackground(new java.awt.Color(255, 204, 51));
        butInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butInfo.setText("INFO SALDO");
        buttonGroup1.add(butInfo);
        butInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInfoActionPerformed(evt);
            }
        });

        butTransfer.setBackground(new java.awt.Color(255, 204, 51));
        butTransfer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butTransfer.setText("TRANSFER");
        buttonGroup1.add(butTransfer);
        butTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTransferActionPerformed(evt);
            }
        });

        butTarik.setBackground(new java.awt.Color(255, 204, 51));
        butTarik.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butTarik.setText("TARIK");
        buttonGroup1.add(butTarik);
        butTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTarikActionPerformed(evt);
            }
        });

        butDaftar.setBackground(new java.awt.Color(255, 204, 51));
        butDaftar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butDaftar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\edit.png")); // NOI18N
        butDaftar.setText("DAFTAR");
        buttonGroup2.add(butDaftar);
        butDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTombolLayout = new javax.swing.GroupLayout(panelTombol);
        panelTombol.setLayout(panelTombolLayout);
        panelTombolLayout.setHorizontalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTombolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTombolLayout.setVerticalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(butLogin)
                .addGap(27, 27, 27)
                .addComponent(butInfo)
                .addGap(27, 27, 27)
                .addComponent(butDeposit)
                .addGap(28, 28, 28)
                .addComponent(butTarik)
                .addGap(28, 28, 28)
                .addComponent(butTransfer)
                .addGap(29, 29, 29)
                .addComponent(butLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(255, 102, 0));
        panelMenu.setLayout(new java.awt.CardLayout());

        panelDaftar.setBackground(new java.awt.Color(255, 204, 102));
        panelDaftar.setForeground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("No Rekening :");

        jLabel2.setText("No Pin :");

        jLabel3.setText("DAFTARKAN NOMOR REKENING DAN PIN ANDA");

        dafAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dafAkunActionPerformed(evt);
            }
        });

        dafPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dafPasActionPerformed(evt);
            }
        });

        dafSubmit.setText("SUBMIT");
        dafSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dafSubmitActionPerformed(evt);
            }
        });

        jLabel7.setText("Saldo Awal: ");

        buttonGroup3.add(pria);
        pria.setText("       Pria");

        buttonGroup3.add(wanita);
        wanita.setText("      Wanita");

        jLabel14.setText("SELAMAT DATANG DI M-BANKING BNI UNLIM");

        javax.swing.GroupLayout panelDaftarLayout = new javax.swing.GroupLayout(panelDaftar);
        panelDaftar.setLayout(panelDaftarLayout);
        panelDaftarLayout.setHorizontalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dafAkun)
                    .addComponent(dafPas)
                    .addGroup(panelDaftarLayout.createSequentialGroup()
                        .addComponent(dafSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wanita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(saldoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(138, 138, 138))
        );
        panelDaftarLayout.setVerticalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dafAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dafPas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(saldoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDaftarLayout.createSequentialGroup()
                        .addComponent(pria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wanita))
                    .addComponent(dafSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        panelMenu.add(panelDaftar, "card8");

        menuLogin.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setText("SILAHKAN LOGIN TERLEBIH DAHULU");

        jLabel5.setText("No Rekening :");

        jLabel6.setText("No Pin          : ");

        logSubmit.setText("SUBMIT");
        logSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLoginLayout = new javax.swing.GroupLayout(menuLogin);
        menuLogin.setLayout(menuLoginLayout);
        menuLoginLayout.setHorizontalGroup(
            menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLoginLayout.createSequentialGroup()
                .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuLoginLayout.createSequentialGroup()
                                .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logRek, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(logPas)))))
                    .addGroup(menuLoginLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(logSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        menuLoginLayout.setVerticalGroup(
            menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logRek, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logPas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(logSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        panelMenu.add(menuLogin, "card2");

        suksesLogin.setBackground(new java.awt.Color(102, 102, 255));

        jTextArea1.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(240, 240, 240));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Selamat datang di aplikasi m-banking v1\nBerikut panduan yang dapat digunakan untuk akses aplikasi ini\n1. Untuk menambah saldo anda bisa menekan tombol deposit\n2. Untuk menarik saldo anda bisa melakukan menekan tombol Tarik\n3. Untuk transfer saldo ke rekening orang lain, tekan transfer\n4. Untuk keluar tekan tombol LOGOUT\n\nPERHATIAN:\nAPLIKASI INI SEDANG DALAM TAHAP PENGEMBANGAN\nSETELAH ANDA LOGIN, JANGAN TEKAN TOMBOL DAFTAR DAN LOGIN LAGI\n\n\nSelamat menikmati aplikasi ini");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout suksesLoginLayout = new javax.swing.GroupLayout(suksesLogin);
        suksesLogin.setLayout(suksesLoginLayout);
        suksesLoginLayout.setHorizontalGroup(
            suksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suksesLoginLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        suksesLoginLayout.setVerticalGroup(
            suksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suksesLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        panelMenu.add(suksesLogin, "card9");

        panelDeposit.setBackground(new java.awt.Color(255, 204, 102));

        jLabel8.setText("Masukan Uang  : ");

        prosesDepo.setText("Submit");
        prosesDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesDepoActionPerformed(evt);
            }
        });

        jLabel9.setText("Pastikan saldo yang anda masukan benar");

        javax.swing.GroupLayout panelDepositLayout = new javax.swing.GroupLayout(panelDeposit);
        panelDeposit.setLayout(panelDepositLayout);
        panelDepositLayout.setHorizontalGroup(
            panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositLayout.createSequentialGroup()
                .addGroup(panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepositLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(depoUang, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDepositLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(prosesDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDepositLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        panelDepositLayout.setVerticalGroup(
            panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depoUang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(prosesDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        panelMenu.add(panelDeposit, "card3");

        panelTarik.setBackground(new java.awt.Color(255, 204, 102));

        jLabel10.setText("Tarik Saldo   : ");

        prosesTarik.setText("Submit");
        prosesTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesTarikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTarikLayout = new javax.swing.GroupLayout(panelTarik);
        panelTarik.setLayout(panelTarikLayout);
        panelTarikLayout.setHorizontalGroup(
            panelTarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarikLayout.createSequentialGroup()
                .addGroup(panelTarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarikLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarikSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTarikLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(prosesTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panelTarikLayout.setVerticalGroup(
            panelTarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarikLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelTarikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarikSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(prosesTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        panelMenu.add(panelTarik, "card5");

        panelTransfer.setBackground(new java.awt.Color(255, 204, 102));

        jLabel11.setText("No Rekening yang dituju :");

        jLabel12.setText("Saldo                             :");

        prosesTransfer.setText("Submit");
        prosesTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rekTujuan)
                            .addComponent(saldoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(prosesTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rekTujuan)))
                .addGap(18, 18, 18)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(prosesTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        panelMenu.add(panelTransfer, "card6");

        menuHome.setBackground(new java.awt.Color(255, 204, 102));

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel13.setText("Terimakasih telah menggunakan layanan kami");

        javax.swing.GroupLayout menuHomeLayout = new javax.swing.GroupLayout(menuHome);
        menuHome.setLayout(menuHomeLayout);
        menuHomeLayout.setHorizontalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHomeLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        menuHomeLayout.setVerticalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        panelMenu.add(menuHome, "card9");

        javax.swing.GroupLayout panelDasarLayout = new javax.swing.GroupLayout(panelDasar);
        panelDasar.setLayout(panelDasarLayout);
        panelDasarLayout.setHorizontalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addComponent(panelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDasarLayout.setVerticalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panelDasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dafAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dafAkunActionPerformed
        //
    }//GEN-LAST:event_dafAkunActionPerformed

    private void dafPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dafPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dafPasActionPerformed

    private void dafSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dafSubmitActionPerformed
        

        boolean cek = false;
        if(dafAkun.getText().isEmpty() && dafPas.getText().isEmpty() && saldoUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukan nomor rek, pin, dan saldo terlebih dahulu", "GAGAL", JOptionPane.ERROR_MESSAGE);
        } else if (dafAkun.getText().isEmpty() && !dafPas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukan nomor rek terlebih dahulu", "GAGAL", JOptionPane.ERROR_MESSAGE);
        } else if (dafPas.getText().isEmpty() && !dafAkun.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukan nomor pin terlebih dahulu", "GAGAL", JOptionPane.ERROR_MESSAGE);
        } else if(dafAkun.getText().isEmpty() && dafPas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan nomor pin dan nomor rekening terlebih dahulu", "GAGAL", JOptionPane.ERROR_MESSAGE);
        }else if(dafAkun.getText().isEmpty() || dafPas.getText().isEmpty() || saldoUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Terdapat bagian yang belum anda isi", "GAGAL", JOptionPane.ERROR_MESSAGE);
        }else if(!pria.isSelected() && !wanita.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin anda", "GAGAL", JOptionPane.ERROR_MESSAGE);
        }else if(Integer.parseInt(saldoUser.getText())<0){
            JOptionPane.showMessageDialog(null, "Saldo yang anda masukan harus lebih dari 0", "GAGAL", JOptionPane.ERROR_MESSAGE);
        }
        else{
        String noRek = dafAkun.getText();
        String noPin = dafPas.getText();
        String saldoPengguna = dafAkun.getText();
        int uang = Integer.parseInt(saldoUser.getText());
            for (String i : akun.keySet()) {
                if (i.equals(noRek)) {
                    cek = true;
                    break;
                }
            }
            if (cek == true) {
                JOptionPane.showMessageDialog(null, "Akun telah ada", "GAGAL", JOptionPane.ERROR_MESSAGE);
            } else {
                akun.put(noRek, noPin);
                // saldo
                userSaldo.put(saldoPengguna, uang);
                JOptionPane.showMessageDialog(null, "Akun berhasil terdaftar", "BERHASIl", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        dafAkun.setText("");
        dafPas.setText("");
        saldoUser.setText("");
    }//GEN-LAST:event_dafSubmitActionPerformed

    private void logSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logSubmitActionPerformed
        String noRekLog = logRek.getText();
        String noPinLog = logPas.getText();
        boolean kondisi = false;
        for (String i : akun.keySet()) {
            if (noRekLog.equals(i) && noPinLog.equals(akun.get(i))) {
                penanda = i;
                kondisi = true;
                break;
            }
        }
        if (kondisi == true) {
            JOptionPane.showMessageDialog(null, "Login berhasil", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
            butDaftar.setEnabled(false);
            butLogin.setEnabled(false);
            butDeposit.setEnabled(true);
            butLogout.setEnabled(true);
            butInfo.setEnabled(true);
            butTarik.setEnabled(true);
            butTransfer.setEnabled(true);
            panelMenu.removeAll();
            panelMenu.repaint();
            panelMenu.add(suksesLogin);
            panelMenu.revalidate();
        } else {
            JOptionPane.showMessageDialog(null, "Tidak berhasil Login", "GAGAL", JOptionPane.ERROR_MESSAGE);
        }
        logRek.setText("");
        logPas.setText("");


    }//GEN-LAST:event_logSubmitActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(menuLogin);
        panelMenu.revalidate();
    }//GEN-LAST:event_butLoginActionPerformed

    private void butDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDaftarActionPerformed
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(panelDaftar);
        panelMenu.revalidate();
    }//GEN-LAST:event_butDaftarActionPerformed

    private void butInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInfoActionPerformed
        if (penanda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan Login terlebih dahulu", "GAGAL", JOptionPane.ERROR_MESSAGE);
        } else {
            for (String i : userSaldo.keySet()) {
                if (i.equals(penanda)) {
                    JOptionPane.showMessageDialog(null, "Saldo anda adalah Rp. " + userSaldo.get(i), "INFO SALDO", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_butInfoActionPerformed

    private void prosesDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesDepoActionPerformed
        int uangDidapat = Integer.parseInt(depoUang.getText());
        if(depoUang.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan saldo","Error", JOptionPane.ERROR_MESSAGE);
        }else if(uangDidapat<0){
            JOptionPane.showMessageDialog(null, "Saldo tidak boleh minus","Error", JOptionPane.ERROR_MESSAGE);
        }else{
           for (String i : userSaldo.keySet()) {
            if (i.equals(penanda)) {
                int saldoSebelum = userSaldo.get(i);
                int saldoNow = hitunganDepo(saldoSebelum, uangDidapat);
                userSaldo.put(i, saldoNow);
                JOptionPane.showMessageDialog(null, "Uang berhasil dikirim", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        } 
        }
        depoUang.setText("");
    }//GEN-LAST:event_prosesDepoActionPerformed

    private void butDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDepositActionPerformed
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(panelDeposit);
        panelMenu.revalidate();
    }//GEN-LAST:event_butDepositActionPerformed

    private void butTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTarikActionPerformed
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(panelTarik);
        panelMenu.revalidate();
    }//GEN-LAST:event_butTarikActionPerformed

    private void prosesTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesTarikActionPerformed
        int uangDidapat = Integer.parseInt(tarikSaldo.getText());
        if(tarikSaldo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan saldo","Error", JOptionPane.ERROR_MESSAGE);
        }else if(uangDidapat<0){
            JOptionPane.showMessageDialog(null, "Saldo tidak boleh minus","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            for (String i : userSaldo.keySet()) {
            if (i.equals(penanda)) {
                int saldoSebelum = userSaldo.get(i);
                int saldoNow = saldoSebelum - uangDidapat;
                if (saldoNow >= 0) {
                    userSaldo.put(i, saldoNow);
                    JOptionPane.showMessageDialog(null, "Uang berhasil ditarik", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Saldo anda tidak mecukupi", "GAGAL", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
        }
        }
        tarikSaldo.setText("");
    }//GEN-LAST:event_prosesTarikActionPerformed

    private void butTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTransferActionPerformed
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(panelTransfer);
        panelMenu.revalidate();
    }//GEN-LAST:event_butTransferActionPerformed

    private void prosesTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesTransferActionPerformed
        int uangDidapat = Integer.parseInt(saldoTF.getText());
        String tujuan = rekTujuan.getText();
        if(saldoTF.getText().isEmpty() && rekTujuan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan saldo dan rekening tujuan","Error", JOptionPane.ERROR_MESSAGE);
        }else if(saldoTF.getText().isEmpty() || rekTujuan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan saldo atau rekening tujuan","Error", JOptionPane.ERROR_MESSAGE);
        }else if(uangDidapat<0){
            JOptionPane.showMessageDialog(null, "Saldo tidak boleh minus","Error", JOptionPane.ERROR_MESSAGE);
        }else if(!userSaldo.containsKey(tujuan)){
            JOptionPane.showMessageDialog(null, "Rekening tujuan tidak tersedia","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            userSaldo.put(tujuan, userSaldo.get(tujuan) + uangDidapat);
            userSaldo.put(penanda, userSaldo.get(penanda) - uangDidapat);
            JOptionPane.showMessageDialog(null, "Uang berhasil ditransfer", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
        }
        
        rekTujuan.setText("");
        saldoTF.setText("");
    }//GEN-LAST:event_prosesTransferActionPerformed

    private void butLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogoutActionPerformed
        penanda = "";
        panelMenu.removeAll();
        panelMenu.repaint();
        panelMenu.add(menuHome);
        panelMenu.revalidate();

        butDaftar.setEnabled(true);
        butLogin.setEnabled(true);
        butDeposit.setEnabled(false);
        butLogout.setEnabled(false);
        butInfo.setEnabled(false);
        butTarik.setEnabled(false);
        butTransfer.setEnabled(false);
    }//GEN-LAST:event_butLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new banking().setVisible(true);
            }
        });
    }
    
    public static int hitunganDepo(int a, int b){
        int x = a+b;
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDaftar;
    private javax.swing.JButton butDeposit;
    private javax.swing.JButton butInfo;
    private javax.swing.JButton butLogin;
    private javax.swing.JButton butLogout;
    private javax.swing.JButton butTarik;
    private javax.swing.JButton butTransfer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField dafAkun;
    private javax.swing.JTextField dafPas;
    private javax.swing.JButton dafSubmit;
    private javax.swing.JTextField depoUang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField logPas;
    private javax.swing.JTextField logRek;
    private javax.swing.JButton logSubmit;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuLogin;
    private javax.swing.JPanel panelDaftar;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JPanel panelDeposit;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTarik;
    private javax.swing.JPanel panelTombol;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JRadioButton pria;
    private javax.swing.JButton prosesDepo;
    private javax.swing.JButton prosesTarik;
    private javax.swing.JButton prosesTransfer;
    private javax.swing.JTextField rekTujuan;
    private javax.swing.JTextField saldoTF;
    private javax.swing.JTextField saldoUser;
    private javax.swing.JPanel suksesLogin;
    private javax.swing.JTextField tarikSaldo;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
}
